/**
 * Server-only deep link signing helpers.
 *
 * Signed tokens are used for SENSITIVE or time-limited deep links (e.g. links
 * generated by the backend that should not be tampered with or replayed).
 * Normal content/share links do not need a token.
 */

// Importing `node:crypto` keeps this module server-only (client bundles fail
// to import it), so we don't need the optional `server-only` package.
import crypto from 'node:crypto'
import { deepLinkConfig } from './config'
import { normalizeTarget } from './links'

export interface SignedLinkPayload {
  /** Internal target path, e.g. /post/123. */
  target: string
  /** Optional opaque actor/source id for analytics or scoping. */
  src?: string
  /** Expiry as unix seconds. */
  exp: number
}

function base64url(input: Buffer | string): string {
  return Buffer.from(input)
    .toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '')
}

function fromBase64url(input: string): Buffer {
  const padded = input.replace(/-/g, '+').replace(/_/g, '/')
  return Buffer.from(padded, 'base64')
}

function hmac(data: string): string {
  if (!deepLinkConfig.signingSecret) {
    throw new Error('DEEPLINK_SIGNING_SECRET is not configured')
  }
  return base64url(
    crypto.createHmac('sha256', deepLinkConfig.signingSecret).update(data).digest()
  )
}

/**
 * Create a signed, URL-safe token encoding a target + expiry.
 * @param ttlSeconds Lifetime of the token (default 1 hour).
 */
export function signLinkToken(
  payload: Omit<SignedLinkPayload, 'exp'> & { ttlSeconds?: number }
): string {
  const target = normalizeTarget(payload.target)
  if (!target) throw new Error('Invalid deep link target')

  const body: SignedLinkPayload = {
    target,
    src: payload.src,
    exp: Math.floor(Date.now() / 1000) + (payload.ttlSeconds ?? 3600),
  }
  const encoded = base64url(JSON.stringify(body))
  const sig = hmac(encoded)
  return `${encoded}.${sig}`
}

/**
 * Verify a signed token. Returns the payload if valid + unexpired, else null.
 * Uses a constant-time comparison to avoid signature timing attacks.
 */
export function verifyLinkToken(token: string | null | undefined): SignedLinkPayload | null {
  if (!token) return null
  const [encoded, sig] = token.split('.')
  if (!encoded || !sig) return null

  let expectedSig: string
  try {
    expectedSig = hmac(encoded)
  } catch {
    return null
  }

  const a = Buffer.from(sig)
  const b = Buffer.from(expectedSig)
  if (a.length !== b.length || !crypto.timingSafeEqual(a, b)) return null

  try {
    const payload = JSON.parse(fromBase64url(encoded).toString('utf8')) as SignedLinkPayload
    if (typeof payload.exp !== 'number' || payload.exp < Math.floor(Date.now() / 1000)) {
      return null
    }
    if (!normalizeTarget(payload.target)) return null
    return payload
  } catch {
    return null
  }
}
